const REACT_APP_FIREBASE_API_KEY = "AIzaSyCSYAUEe3uVwUYt9Zu9lHLZweVGia3BJ38";
const REACT_APP_FIREBASE_AUTH_DOMAIN = "chat-app-3e117.firebaseapp.com";
const REACT_APP_FIREBASE_PROJECT_ID = "chat-app-3e117";
const REACT_APP_FIREBASE_STORAGE_BUCKET = "chat-app-3e117.appspot.com";
const REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "569799107383";
const REACT_APP_FIREBASE_APP_ID = "1:569799107383:web:57f693ef6cca29e7ceb0b2";

export {
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
};
